openapi: 3.0.0
info:
  title: Hello World API
  description: A simple API that returns a "Hello World" message.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /:
    get:
      summary: Returns a Hello World message
      description: A simple endpoint that returns a "Hello World" string.
      responses:
        '200':
          description: A successful response with a Hello World message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello World"

  /schema/collection/create:
    post:
      summary: Create a new collection
      parameters:
        - $ref: '#/components/parameters/XStableEventId'
        - $ref: '#/components/parameters/XStableEventCreated'
      requestBody:
        description: Payload for creating a new collection
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/collection/create.json'
      responses:
        '201':
          description: Collection created successfully
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized
        '409':
          description: Conflict, event-id already processed

  /schema/collection/update:
    post:
      summary: Update an existing collection
      parameters:
        - $ref: '#/components/parameters/XStableEventId'
        - $ref: '#/components/parameters/XStableEventCreated'
      requestBody:
        description: Payload for updating an existing collection
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/collection/update.json'
      responses:
        '200':
          description: Collection updated successfully
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized
        '404':
          description: Collection not found
        '409':
          description: Conflict, event-id already processed

  /schema/collection/delete:
    post:
      summary: Deletes an existing collection
      parameters:
        - $ref: '#/components/parameters/XStableEventId'
        - $ref: '#/components/parameters/XStableEventCreated'
      requestBody:
        description: Payload for deleting an existing collection
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/collection/delete.json'
      responses:
        '200':
          description: Collection updated successfully
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized
        '404':
          description: Collection not found
        '409':
          description: Conflict, event-id already processed

components:
  schemas: {}
  parameters:
    XStableEventId:
      name: x-stable-event-id
      in: header
      description: Client generated event identifier, should be UUID v7
      schema:
        type: string
    XStableEventCreated:
      name: x-stable-event-created-on
      in: header
      description: Client event creation timestamp
      schema:
        type: number

