package com.stabledata

import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.testing.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AuthTest {

    @Test
    fun testRoot() = testApplication {
        application {
            module()
        }

        val response = client.get("/")
        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("Hello World!", response.bodyAsText())
    }

    @Test
    fun `generate JWT` () {
        val jwt = generateJwtTokenWithCredentials(UserCredentials("ben"))
        System.out.println(jwt)
    }

    @Test
    fun `verify JWT` () {
        // this token was generated by jose lib.
        // of note, others did not seem to work
        val v = verifyToken("eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImJlbiJ9.92gaKus91nY1UP22qwfDABP7o1l59kJ2HbnBEfwiyqc")
        assertNotNull(v)
    }
}