package com.stabledata

import com.stabledata.plugins.UserCredentials
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.testing.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

const val NODE_GENERATED_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImJlbiJ9.92gaKus91nY1UP22qwfDABP7o1l59kJ2HbnBEfwiyqc"
class AuthTest {

    @Test
    fun `authorizes calls with ktor generated tokens` () = testApplication {
        application { module() }

        val token = generateTokenForTesting()
        val response = client.get("/secure") {
            headers {
                append(HttpHeaders.Authorization, "Bearer $token")
            }

        }
        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("secured", response.bodyAsText())
    }

    @Test
    fun `requires team to claim to match` () = testApplication {
        application { module() }

        val token = generateJwtTokenWithCredentials(UserCredentials("ben@testing.com", "wrong.team"))
        val response = client.get("/secure") {
            headers {
                append(HttpHeaders.Authorization, "Bearer $token")
            }

        }
        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }

    @Test
    fun `generate JWT` () {
        val jwt = generateTokenForTesting()
        println(jwt)
    }

    @Test
    fun `verify JWT` () {
        configureLogging()
        // this token was generated by jose lib.
        // of note, other libs did not seem to work
        val v = verifyToken(NODE_GENERATED_TOKEN)
        assertNotNull(v)
    }
}