name: Synchro Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: "Synchro Image"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: GCP Workload Identity Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: "Auth to AR"
        run: gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Inspect OIDC Token
        run: |
          curl -H "Authorization: Bearer ${{ steps.auth.outputs.id_token }}" \
            "https://token.actions.githubusercontent.com/.well-known/openid-configuration" | jq .

      - name: Retrieve OIDC Token
        id: retrieve-oidc-token
        run: |
          echo "Retrieving OIDC Token..."
          export OIDC_TOKEN=$(curl -s -H "Authorization: Bearer ${{ steps.auth.outputs.id_token }}" \
            "https://token.actions.githubusercontent.com/.well-known/openid-configuration/jwks")
          echo "OIDC Token: $OIDC_TOKEN"

      - name: Decode OIDC Token
        run: |
          echo "${{ steps.retrieve-oidc-token.outputs.OIDC_TOKEN }}" | base64 --decode | jq .

      - name: "Build Docker Image"
        run: |
          docker build . \
            -f Dockerfile \
            -t us-east4-docker.pkg.dev/surface-420608/stable/synchro-kotlin:${GITHUB_SHA::6} \
            -t us-east4-docker.pkg.dev/surface-420608/stable/synchro-kotlin:latest

      - name: "Push Docker Image to AR"
        run: |
          docker push us-east4-docker.pkg.dev/surface-420608/stable/synchro-kotlin:${GITHUB_SHA::6}
          docker push us-east4-docker.pkg.dev/surface-420608/stable/synchro-kotlin:latest
